#  ___ _ _      _   _    ___         _           _
# | __| (_)__ _| |_| |_ / __|___ _ _| |_ _ _ ___| |
# | _|| | / _` | ' \  _| (__/ _ \ ' \  _| '_/ _ \ |
# |_| |_|_\__, |_||_\__|\___\___/_||_\__|_| \___/_|
#         |___/                        by Spazzinq
# Donate: https://spazzinq.org/donate
# Discord: https://spazzinq.org/discord
# Issue Tracker: https://github.com/Spazzinq/FlightControl/issues
# Spigot Page: https://www.spigotmc.org/resources/flightcontrol.55168/
# Permissions: https://spazzinq.org/flightcontrol/permissions

settings:
  # Updates the config automatically and adds new features
  auto_update: true
  # Enables flight automatically (no command necessary)
  auto_enable_flight: true
  # The default speed is 1.0 and matches Essentials's /flyspeed values (0-10)
  flight_speed: 1.0
  # Supports: CombatTagPlus, CombatLogX, CombatLogPro, AntiCombatLogging, DeluxeCombat
  # NOTE: disable flight disabling/enabling in the combat plugin's config to prevent issues
  disable_flight_in_combat: false
  # Prevents fall damage when flight is disabled mid-air by FlightControl
  prevent_fall_damage: false
  # Supports: EssentialsX, PremiumVanish, SuperVanish
  # Prevents flight disabling while in vanish
  vanish_bypass: true

# NOTE: this feature is resource intensive and may cause performance issues
nearby_disable:
  # Disables flight when a player is within a certain block range (set to -1 to disable)
  range: -1
  # Supports: Factions by MassiveCraft, FactionsUUID, SavageFactions
  # Makes the "range" setting only for faction enemies
  factions_enemy: true

trail:
  enabled: false
  # 1.8 Particle Info: https://spazzinq.org/flightcontrol/particles/1
  # 1.15 Particle Info: https://spazzinq.org/flightcontrol/particles/2
  particle: "CLOUD"
  amount: 2
  # Please look at the particle info links above to know which particles can change color
  # Color picker (RBG): https://www.google.com/search?q=color+picker
  rgb: "0,0,0"

sounds:
  # Plays the sounds on EVERY double tap of the space bar
  every_enable: false
  every_disable: false
  # Please use the sound names from the "Sound Event" column
  # 1.8 List: https://minecraft.gamepedia.com/Sounds.json/Java_Edition_values_before_1.9
  # 1.15 List: https://minecraft.gamepedia.com/Sounds.json/Java_Edition_values
  enable:
    sound: "NONE"
    pitch: 1
    volume: 1
  disable:
    sound: "NONE"
    pitch: 1
    volume: 1
  # "can_enable" and "cannot_enable" are used when "auto_enable" is false
  # or if the player disables their own flight with /fly
  can_enable:
    sound: "NONE"
    pitch: 1
    volume: 1
  cannot_enable:
    sound: "NONE"
    pitch: 1
    volume: 1